#!/bin/zsh

has_sudo() {
    local prompt

    prompt=$(sudo -nv 2>&1)
    if [ $? -eq 0 ]; then
    echo "has_sudo__pass_set"
    elif echo $prompt | grep -q '^sudo:'; then
    echo "has_sudo__needs_pass"
    else
    echo "no_sudo"
    fi
}

system_type=$(uname -s)
HAS_SUDO=$(has_sudo)


if [ "$system_type" = "Linux" ] && [ "$HAS_SUDO" != "no_sudo" ] ; then
    echo "Installing packages"
    sudo apt install neovim fzf
fi

if command -v nvim >/dev/null 2>&1; then
    echo "Bootstrapping neovim"
    # install vimplug, alternatively you can do this in init.vim
    sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
           https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    nvim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
else
    echo "Bootstrapping vim"
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi

echo "Configuring git"
git config --global user.email "im.qianmian.yu@gmail.com"
git config --global user.name  "qianmian yu"
git config --global pull.rebase true
git config --global credential.helper store

echo "Bootstrapping prezto"
git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
setopt EXTENDED_GLOB
for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
  ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
done

echo "Bootstrapping tmux"
cd
git clone https://github.com/gpakosz/.tmux.git
ln -s -f .tmux/.tmux.conf

if ! grep -q '# added by yadm' ~/.zshrc; then
  cat 'source <(cat ~/.zsh-contrib/*.zsh)' >> ~/.zshrc
fi
